### PR TITLE
Ansible start

### PR DESCRIPTION
**Pull request by kylerisse**
## Description of PR
Starting build out of Ansible CM files, including functional vagrant environment

## Previous Behavior
No ansible or documented server list

## New Behavior
Some ansible, documented server list, but much work to do

## Tests
Local Vagrant

### CODE REVIEW

**Comment by owendelong** [comment]
Kyle, Please resolve the conflicts for pi/gold_image.txt and then merge. I've approved the commit but I'm not sure how to identify/resolve the conflict. My git foo is not that strong. ;)

**Comment by sarcasticadmin** [comment]
@kylerisse this looks good too! Thanks for getting started on the network services! Just resolve the conflicts like @owendelong mentioned.

@owendelong dont worry about your git fu here I typically have the contributor handle resolving their own conflicts.

**Comment by kylerisse** [comment]
resolved the conflict, sticking with the rule of not merging my own PR. this sets a baseline for ansible, not quality for complete yet. you should be able to get up a working vagrant environment with this.

**Comment by owendelong** [comment]
I think as long as your PR has been reviewed by at least one other person, merging it should be fine.

Owen

**Comment by sarcasticadmin** [comment]
@owendelong [personal preference disclaimer]: Id rather have someone else on the team merge it since things may drift from the initial approval. But as long as everyone on the teams on the same page I'm fine with whatever process we want go with.

@kylerisse thanks for resolving this!

**Pull request merged**
