### PR TITLE
[READY] ci: add package and nixos config builds

### PR DESCRIPTION
**Pull request by djacu**
## Description of PR

Only 1 package and 0 nixos configurations where being built in CI. Now they all are.

### CODE REVIEW

**Comment by djacu** [comment]
Me writing YAML code

**Review by sarcasticadmin — APPROVED** [review]
nix test all the things!

**Comment by kylerisse** [comment]
> @sarcasticadmin this PR introduced regression #781 . Matrix gifs are fun but can we allocate some of that time to actually testing and reviewing what we implement?

My apologies. This was totally unnecessary…

**Comment by sarcasticadmin** [comment]
all good, I was excited for the nixosConfoguration build tests. Never knew about a cache rate limit until yesterday but I think the new pr #783 should be a good middle ground

**Comment by djacu** [comment]
It's ok man. I didn't realize the magic cache would cause issues. But as we learned earlier this year, even GH will rate limit GH.

**Pull request merged**
