### PR TITLE
[READY] Adding links to maps pdfs

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of PR
@sbibayoff I added these to `s3` instead of directly in git. That way theres no having to mess with `git-lfs`. This was my alternative to #124. Let me know what you think.

Sorry for the delay.

## Previous Behavior
We didnt have maps

## New Behavior
Now we have maps for the Pasadena Convention Center from 16x 

## Tests
Links work

### CODE REVIEW

**Comment by sbibayoff** [comment]
Hey Rob,

This works. But would it be better to have them on the wiki as one of the suggestion you made? I don't know if scale has an s3 account, but would prefer to have all scale stuff under a scale "property".

just a thought

**Comment by sarcasticadmin** [comment]
@sbibayoff I totally agree. I just put the pdfs in my public s3 bucket for the time being since that's also where the firmware for the switches currently resides: https://github.com/socallinuxexpo/scale-network/tree/master/switch-configuration#firmware

I raised the issue on the tech mailing list, we'll see what we can do about getting it into some that Scale itself can manage.

**Comment by sarcasticadmin** [comment]
@owendelong we actually dont want to `merge` master into `feature` branches. Typically if we need to Id recommend `rebasing`. `git` doesnt really make this obvious though. Ill take care of undoing your `merge` on this branch and then we can merge this for now

**Comment by sarcasticadmin** [comment]
@owendelong I didnt realize there was a merge conflict with the `README.md` and thats why you merged `master`. Its a really annoying feature of github since it convolutes the history. Ill show you what I mean during the show. Regardless this is all fixed and Ill `merge`

**Comment by owendelong** [comment]
Ah… OK… Now it makes sense. Sorry if I created a problem. Was confused by it, but decided to try and do something useful rather than just leave it sitting around untouched.

Thanks for cleaning up my gitmess again. ;-)

BTW, how would you feel about pushing to migrate to bitbucket instead of GitHub?

The reason I suggest this is that bitbucket has IPv6 support while GitHub doesn’t.

Owen

**Comment by sarcasticadmin** [comment]
No worries @owendelong! I appreciate the effort and its something I really wish was clarified. If I cant read the `git log` then whats the point! `rebase` makes this possible

Umm I havent had the best experience with bitbucket, but if you want to raise this on the tech mailing list to get the discussion going Ill certainly give my .02 cents

**Pull request merged**
