### PR TITLE
Add "berkhan" user in "wheel" group

### PR DESCRIPTION
**Pull request by BerkhanBerkdemir**

### CODE REVIEW

**Review by ruebenramirez — APPROVED** [review]
🚀

**Review by ruebenramirez — CHANGES_REQUESTED** [review]
TODO: patch up the deleted curly brace

**Comment by BerkhanBerkdemir** [comment]
Now, it's ready. Thanks @ruebenramirez

**Review by ruebenramirez — APPROVED** [review]
🚀

**Review by ruebenramirez — APPROVED** [review]

**Review by kylerisse — APPROVED** [review]
welcome aboard @BerkhanBerkdemir !
thanks @ruebenramirez

**Pull request merged**
