### PR TITLE
[READY] - init massflash for APs via kea dhcpd

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of PR
Fixes: #385

At the past scale work party we were able to `massflash` the entire set of 100+ APs in about 2 hours. The result of the teams efforts is the following script and configuration that made this possible

## Previous Behavior
- Used to have to update each AP via the existing flash (soloflash) script

## New Behavior
- `massflash` process exists
- `kea.tmpl` for setting up a `massflash` dhcpd server

## Tests
- Flashed 100+ aps at the last workparty for scale 19x

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
Going to merge this tomorrow unless anyone has issues/concerns with this as it currently stands

**Review by owendelong — COMMENTED** [review]
This is some really awesome work, Rob... Thanks for putting it together and working through all the kinks!

**Review by owendelong — APPROVED** [review]
Oops... Forgot to click approve last time.

**Comment by owendelong** [comment]
It’s been merged.

Owen

**Pull request merged**
