### PR TITLE
[READY] Reallocate switches

### LINKED ISSUE #775: reallocate switches
organize the switches in numberic order in the carts

switches 1-11 noc cart
switches 12-23 lower conf cart
switches 24-39 expo cart
switches 40-51 ballroom cart
switch 52 monitor cart

new order is:

1 NOC
2 ConfIDF
3 NW-IDF
4 NE-IDF
5 ExpoIDF
6 Expo-Catwalk
7 MassFlash
8 AVSwitch
9 Rm209-210
10 Rm211
11 Rm214
12 Rm101-102
13 Rm103
14 Rm104
15 Rm105
16 Rm106
17 Rm107
18 SpareA
19 SpareB
20 SpareC
21 SpareD
22 SpareE
23 SpareF
24 ExpoAW
25 ExpoA1
26 ExpoA2
27 ExpoA3
28 ExpoA4
29 ExpoA5
30 ExpoB1
31 ExpoB2
32 ExpoB3
33 ExpoB4
34 ExpoB5
35 ExpoC1
36 ExpoC2
37 ExpoC3
38 ExpoC4
39 ExpoC5
40 BallroomA
41 BallroomB
42 BallroomC
43 BallroomDE
44 BallroomF
45 BallroomG
46 BallroomH
47 SpareG
48 SpareH
49 SpareI
50 SpareJ
51 SpareK
52 RegDesk

### PR DESCRIPTION
**Pull request by kylerisse**
Fixed #775 

## Description of PR
This is a mass renaming of all the switches per work party 1. It also disables the data validation for switch noise level as that will be going away.

## Previous Behavior

- switches had previous IDs
- noise level data validation only allowed for specific values

## New Behavior

- switches have new IDs supplied by @davidelang 
- noise level data validation now passes with any value, no longer strict

## Tests

1. spot checked a couple of entries in the output
2. ran `nix build -L .#checks.x86_64-linux.pytest-facts` to validate TSV contents still valid (found noise level issue and modified behavior.
3. ran `nix build -L .#checks.x86_64-linux.perl-switches` and verified the switch configurations were generated and script exit 0
4. Asking @davidelang to check this PR and approve if it all looks good.

### CODE REVIEW

**Comment by davidelang** [comment]
@owendelong this looks good to me. There are two switches we need to replace #5 and #51 (formerly #54)
I think you probably want to set some default configs for the spares, but I don't know what you would want to do with them (1/2 for rooms for each side? set some as idf or booth? don't care because you will reassign them when they go to get used??)

**Comment by owendelong** [comment]
I had previously set them all up as cfRoom just as a placeholder and to minimize the likelihood of conflict if they got plugged in to a switch port in the NOC.

**Review by owendelong — COMMENTED** [review]
On cursory look, this seems sane. We should be prepared for "interesting" flash results.

I'll try to catch anything glaring during the sticker generation process on its next run.

**Review by owendelong — APPROVED** [review]

**Comment by davidelang** [comment]
We will also need to move fiber cards between switches.

David Lang

**Pull request merged**
