### PR TITLE
[READY] - monitoring: grafana and prometheus service enabled

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of PR

Relates to: #641 #567 

This enables the foundations for grafana and prometheus services on the monitoring vm. I originally wanted to leverage `collectd` instead of prometheus but that ended up being more trouble than it was worth with influxdbv2 or graphite. Landing on prometheus should give us a good base and we can restrict the access to the webserver for scaping in a few ways. Grafanas admin password is currently being set on first login when creating a VM.

Currently we still need to:

  - Enable TLS
  - Generate a static configs for scapers
  - Enable prometheus exporters on Servers
  - Enable prometheus exporters on APs
  - Enable prometheus exporters on Pis

This will be done in follow up PRs if this initial approach is approved.

Prometheus is also added as a common nixos module so that it can be consumed from other machines.

ss-202311251700943674

## Previous Behavior
- Monitoring server was missing from scale-network automation

## New Behavior
- Monitoring server provisioned via a nixos config

## Tests

From another nixos machine:
```
nix build .#nixosConfigurations.monitor.config.system.build.vm -L
export QEMU_NET_OPTS="hostfwd=tcp::2222-:22"
./result/bin/run-nixos-vm
```

Setting up port forwarding to expose on `localhost:8000`:
```
ssh -o StrictHostKeyChecking=no -p 2222 rherna@127.0.0.1 -L 8000:127.0.0.1:80
```

### CODE REVIEW

**Comment by nixinator** [comment]
Nice work on this Rob, i'm currently testing your changes... 


ON TLS 

Were going to require certs and i presume ACME is out because it's on internal ipv4 subnet.

Hmmm....

We could get everything running on ipV6, then we could get ACME , if acme supports  ipv6 however. This would require our internal servers to have public ipV6 DNS entries.. I don't know how i feel about that... maybe i should feel good.

Failing that were going to need our own CA, and start shunting certs about, which might be a massive PITA. However it would be a good opportunity to build a nix internal ACME system along the lines of  https://smallstep.com/blog/private-acme-server/

however, this may not be an insignificant amount of work.

**Comment by davidelang** [comment]
perfect is the enemy of good enough :-)

David Lang

**Comment by owendelong** [comment]
If people don’t mind importing my Root certificate (available at http://www.delong.com <https://www.delong.com/>), then I have a CA already set up that we can use to issue all the certs we need.

Owen

**Comment by nixinator** [comment]
I have to remember that @owendelong doesn't use the internet, he *is* the internet. ;-)

**Comment by owendelong** [comment]
Ah, but what will really bake your mind is that there is no such thing as “The Internet”.

What we call “The Internet” is a very loosely coupled set of networks that happen to have agreed to use the same protocol(s) and exchange traffic with each other.

Owen

**Comment by owendelong** [comment]
> On Nov 27, 2023, at 15:58, Robert James Hernandez ***@***.***> wrote:
> 
> 
> Nice work on this @sarcasticadmin <https://github.com/sarcasticadmin> , i'm currently testing your changes...
> 
> @nixinator <https://github.com/nixinator> thanks for testing.
> 
> however, this may not be an insignificant amount of work.
> 
> At this point my plan is to do one of the following:
> 
> Issue a self signed certificate at runtime. This will require anyone connecting to web ui to "trust on first use" but thats good enough in my book for the small number of users for this service.
> Make grafana web service listen only on loopback and require that users to port forward via SSH to get to the web ui. Plus side here is that this doesnt require any self signed certs and we can leave it on http.
> Sounds like in general were good with this approach though, Ill mark it as READY
> 

Why not use my CA? Is there a problem with, perhaps using the same wildcard cert on every box?

Owen

**Comment by sarcasticadmin** [comment]
> Why not use my CA? Is there a problem with, perhaps using the same wildcard cert on every box?

Its mainly to avoid the bootstrap problem of getting the private key on the VM in the first place. Many ways to do this but trying to keep it to a low level of effort.

**Review by owendelong — APPROVED** [review]
Most of this looks very "rusty". Ugh.

I guess we have to use the tools that are available.

**Comment by owendelong** [comment]
> On Nov 27, 2023, at 23:18, Robert James Hernandez ***@***.***> wrote:
> 
> 
> Why not use my CA? Is there a problem with, perhaps using the same wildcard cert on every box?
> 
> Its mainly to avoid the bootstrap problem of getting the private key on the VM in the first place. Many ways to do this but trying to keep it to a low level of effort.
> 
TBH, I’m fine with just storing the private key in the server image. Since the cert isn’t being used for authentication and impersonation of our server is a pretty low risk scenario in this case, I don’t see guarding that private key as paramount.

**Comment by owendelong** [comment]
I suspect we will eventually build a full time password vault of some form (IIRC, Rob had some thoughts in this area) and we can probably just use that.

Owen

**Comment by nixinator** [comment]
sure my current flavour of secret management is secrix.

It's rather nice.. .

https://journal.platonic.systems/introducing-secrix/

**Pull request merged**
