### PR TITLE
od.17.01

### PR DESCRIPTION
**Pull request by owendelong**
## Description of PR
Multiple changes to switch configuration process preparing for SCaLE17x
Resolves Issues #133 (Update Automation to create vendor VLANs) and  #135 (Address Switch Noise Concerns) 

## Previous Behavior
PVLANs were generated

## New Behavior
Normal VLANs and local routing on the Expo switches are generated
Firewall rules are generated (though not currently applied to interfaces)
DHCP forwarding is still an open item.

These are issues #139 #140, respectively.

Also addressed some lingering ##FIXME## comments in the code. (Low hanging fruit)

## Tests
Ran scripts locally and reviewed results.

### CODE REVIEW

**Comment by owendelong** [comment]
This PR is for incomplete software, but even if I don't get the two issues corrected, it leaves us with configuration files that are much closer to what we need than what we would get if I didn't check it in as is, so I decided to push it and continue working on it for now.

**Comment by kylerisse** [comment]
Thanks Owen! I see that Circle is failing here. This is not the result of anything you've done. It looks like this branch is working off an old pre-Circle CI master. Sorry about that hassle.

There are just growing pains of having added CI for testing until all stale branches get past #130. 

To resolve this could you please rebase this branch against current master and re push? That should pick up the circle config and get the tests to run. The process is in the "Common Scenarios" section at https://github.com/socallinuxexpo/scale-network/blob/master/CONTRIBUTING.md although the final step replace `develop` with `master` I believe.

**Comment by owendelong** [comment]
> On Feb 27, 2019, at 22:15 , kylerisse <notifications@github.com> wrote:
> 
> Thanks Owen! I see that Circle is failing here. This is not the result of anything you've done. It looks like this branch is working off an old pre-Circle CI master. Sorry about that hassle.
> 
> There are just growing pains of having added CI for testing until all stale branches get past #130 <https://github.com/socallinuxexpo/scale-network/pull/130>.
> 
> To resolve this could you please rebase this branch against current master and re push? That should pick up the circle config and get the tests to run. The process is in the "Common Scenarios" section at https://github.com/socallinuxexpo/scale-network/blob/master/CONTRIBUTING.md <https://github.com/socallinuxexpo/scale-network/blob/master/CONTRIBUTING.md> although the final step replace develop with master I believe.
> 
> 

Sure, I’ll try to figure that out momentarily…

Owen

**Comment by owendelong** [comment]
OK… I did all that up to and including the push.

Do I need to close this PR and create a new one, or, is there some other bit I’m missing?

Owen

**Comment by kylerisse** [comment]
No need for new PR as this should be fine but the circle file still not in branch. I could have given you bunk info. We'll need the pro stylings of @sarcasticadmin to advise the path. Again, sorry for the hassle. These tests shouldn't cause friction long term, just in the transition period on this one. We should await Rob's instructions.

**Comment by owendelong** [comment]
We’re getting together on hangouts to sort it out.

Owen

**Comment by owendelong** [comment]
Turns out I’m an idiot and can’t keep the difference between the following straight in my head:

	od.17.01
	OD.17.01
	Od.17.01

Rob helped me fix it all.

Owen

**Pull request merged**
