### PR TITLE
[READY] DHCP services

### PR DESCRIPTION
**Pull request by kylerisse**
## Description of PR
Add DHCP services for IPv6 and IPv4 to core servers

## Previous Behavior
no DHCP

## New Behavior
Dynamically generated DHCP pools sourced from vlans.d. Full feature list in ansible/README.md.

## Tests
1. bring up vagrant environment (cd ansible; vagrant up)
2. `alias ans="ansible -u kyle -i inventory.py"`
3. `ans server4 -b -a "dhclient -6 -s server1"` (generates some request traffic)
4. `ans server3 -b -a "dhclient -6 -s server2"` (generates some request traffic)
5. `ans core -b -a "systemctl status isc-dhcp-server"` (verify ipv4 services)
6. `ans core -b -a "systemctl status isc-dhcp-server6"` (verify ipv6 services)
7. `ans core -b -a "cat /var/log/dhcp.log"` (review dhcp logs, due to the nature of vagrant testing server2 wont necessarily have real entries)
8. `ans core -a "cat /etc/dhcp/dhcpd6.conf.subnets"` (review dynamic ipv6 pools for sanity)
9. `ans core -a "cat /etc/dhcp/dhcpd.conf.subnets"` (review dynamic ipv4 pools for sanity)
10. `ans core -a "ls -al /etc/dhcp/backup"` (verify timestamped backup
(regression for DNS)
11. `ans servers -a "dig -t aaaa expo10.scale.lan"`
12. `ans servers -a "dig -x 2001:470:f325:103::200:34"`
13. `ans core -a "cat /etc/bind/db.10.ip4.arpa.records"`
14. `ans core -a "cat /etc/bind/db.ip6.arpa.records"`
15. `ans core -a "cat /etc/bind/db.scale.lan.records.switches"`
16. `ans core -a "cat /etc/bind/db.scale.lan.records.servers"`

### CODE REVIEW

**Comment by kylerisse** [comment]
@owendelong hope it's OK, commented out the MSFT SVLAN as that has been cancelled

@sarcasticadmin sorry for the messy PR, merge issues

**Comment by owendelong** [comment]
Yeah, that’s no problem.

Owen

**Comment by owendelong** [comment]
You and Rob should be primary reviewers at this point. My ability to do anything with git hub between now and the show
will be very spotty at best.

Owen

**Comment by kylerisse** [comment]
understood, thank you

**Comment by kylerisse** [comment]
haha, the theme is that IPv6 comes before IPv4, that's part of the fun. The documentation should reflect that priority. I've tried to maintain that throughout.

ipv4 and ipv6 dns: We have to initialize them as empty somewhere. We can't populate them until the server list exists which comes later in lines 237-242, where we test to ensure that dns1 is the server in the same building, dns2 the other. If you try to reference those keys without initializing them earlier it throws key errors. I remember considering moving the initialization down around 237 but thinking by keeping it in the vlan section it doubles as slim documentation. At a quick glance some non-me person would have an immediate idea of all properties a vlan includes. I've made a few decisions like that to hopefully make it easier to pickup and maintain, using "global" variables and minimizing use of return functions to encapsulate complexity only.

**Comment by owendelong** [comment]
Thanks for the explanation.

That’s why you’re the ansible expert and I’m just along for the ride on that part. ;-)

Well done.

Owen

**Comment by kylerisse** [comment]
HA, I'm amateur at best. btw, you're right despite my pointless rambling, i can remove those initializations. I think it's an artifact of trying to do it by figuring out the vlan before appending to servers. I switched to using the array's index. Thanks for the heads up, i was able to ditch in latest. this is why code review is good. thank you.

**Comment by owendelong** [comment]
I really was just curious about it. It wasn’t a criticism or request to eliminate it, but I wanted to make sure it wasn’t an oversight and also better understand the process. Thanks for all your work on this.

Owen

**Comment by kylerisse** [comment]
dude, didn't take it that way. using it as an opportunity to learn more
ansible, git, and python. id say the process is working. i like the
interesting requirements you guys introduce to be honest [building
preference for services, transient team, no IPv4 on multiple vlans, tab
file source of truth, etc], good excuse to play with the weird data
structure and more complex jinja templates, and cutting corners/reinvent
wheels that wouldn't be right in real life environment. looking forward to
the show, i learn many interesting things when we're all together. thx for
the nice words. -Kyle

**Pull request merged**
