### PR TITLE
[READY] - Update steveb_id_rsa.pub

### PR DESCRIPTION
**Pull request by sbibayoff**
updating my key

## Description of PR
updating my key for use with scale 19x

## Previous Behavior
old key

## New Behavior
Remove this section if not relevant

## Tests
How was this PR tested?
hopping is works ;-)

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
@sbibayoff I went head and helped you out since that change that initially failed was due to the `golden` files for openwrt template testing.

You would normally need to have `gomplate` installed then run:

```
cd openwrt
make golden-update
```

This will regenerate the templates that we tracked for testing purposes.

Should be all set now, but Ill let others on the team review this change as well

**Review by sarcasticadmin — APPROVED** [review]

**Comment by sbibayoff** [comment]
Thanks Rob, completely forgot about that. Will keep in mind for future pull requests

**Comment by sarcasticadmin** [comment]
@sbibayoff why did we close this? seems totally fine, going to reopen

**Review by kylerisse — APPROVED** [review]
lgtm

**Pull request merged**
