### PR TITLE
[READY] Refactor to support ipq806x (atheros 10k)

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of PR
* Refactoring to support multiple architectures as mentioned in #120
* Fixes `.ssh` default permissions #122 
* Fixes `zabbix_agentd` configuration error #132 

Initially I was attempting to use the old build process and configurations since the c2600 has similar characteristics to WNDR3800. Unfortunately the networking configuration needs to be changed, from my testing I need to include the following `switch_vlan` configurations in `/etc/config/network`:

```
config switch_vlan
        option device 'switch0'
        option vlan '0'
        option ports '1 2 3 4 6t'
config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '5 0t'    
```

Along with dropping the `enable_vlan4k 1` setting for `config switch` section that does not appear to be supported by the c2600 switch:

```
~# swconfig dev switch0 help
switch0: gpio-0(Atheros AR8337), ports: 7 (cpu @ 0), vlans: 128             
      --switch
        Attribute 1 (int): enable_vlan (Enable VLAN mode)
        Attribute 2 (none): reset_mibs (Reset all MIB counters)
        Attribute 3 (int): enable_mirror_rx (Enable mirroring of RX packets)
        Attribute 4 (int): enable_mirror_tx (Enable mirroring of TX packets)
        Attribute 5 (int): mirror_monitor_port (Mirror monitor port)
        Attribute 6 (int): mirror_source_port (Mirror source port)
        Attribute 7 (int): arl_age_time (ARL age time (secs))
        Attribute 8 (string): arl_table (Get ARL table)
        Attribute 9 (none): flush_arl_table (Flush ARL table)
        Attribute 10 (int): igmp_snooping (Enable IGMP Snooping)
        Attribute 11 (int): igmp_v3 (Enable IGMPv3 support)
        Attribute 12 (none): apply (Activate changes in the hardware)
        Attribute 13 (none): reset (Reset the switch)
     --vlan
        Attribute 1 (int): vid (VLAN ID (0-4094))
        Attribute 2 (ports): ports (VLAN port mapping)
     --port
        Attribute 1 (none): reset_mib (Reset single port MIB counters)
        Attribute 2 (string): mib (Get port's MIB counters)
        Attribute 3 (int): enable_eee (Enable EEE PHY sleep mode)
        Attribute 4 (none): flush_arl_table (Flush port's ARL table entries)
        Attribute 5 (int): igmp_snooping (Enable port's IGMP Snooping)
        Attribute 6 (int): vlan_prio (Port VLAN default priority (VLAN PCP) (0-7))
        Attribute 7 (int): pvid (Primary VLAN ID)
        Attribute 8 (unknown): link (Get port link information) 
```

The goal will be to keep the original `WAN` port for troubleshooting with static IP and then bridge the original `LAN` ports and enable DHCP. Will discuss this more in the team call.

Other than that all the custom pkgs that are used by our build look intact, so we'll be able to build off whats already been done there.

## Previous Behavior
* `.ssh` had wrong permissions which didnt allow users to use authorized_keys
* `zabbix_agentd` was misconfigured and wouldnt start
* Could only build Netgear WNDR370v2-3800[ch]

## New Behavior
* Refactoring to support multiple architectures as mentioned in #120
* Fixes `.ssh` default permissions #122 
* Fixes `zabbix_agentd` configuration error #132 

## Tests
How was this PR tested? Obviously the CI tests! The `golden` tests very helpful across these multiarch templates and builds.

And the `serverspec` tests have already come in handy. I caught an issue with `rsyslog` and it wasnt building correctly on the `18.06` pkg branch against an `ipq806x` target. So thats already saved me a few headaches :)

See below for more specifics on actually image testing on hardware:

### ar71xx
Loading the firmware via `tftp`:

```
BusyBox v1.30.0 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r0-ddf08af
 -----------------------------------------------------
root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.93 #0 Wed Feb 27 06:27:32 2019 mips GNU/Linux
root@OpenWrt:~# cat /etc/openwrt_version
r0-ddf08af
root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.93 #0 Wed Feb 27 06:27:32 2019 mips GNU/Linux
root@OpenWrt:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r0-ddf08af'
DISTRIB_TARGET='ar71xx/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r0-ddf08af'
DISTRIB_TAINTS='no-all busybox'
root@OpenWrt:~#
````

`serverspec`:

```
~$ rake spec TEST_TYPE=openwrt TARGET_HOST=192.168.254.100                                                                                                                                                
/usr/home/rherna/.rbenv/versions/2.5.1/bin/ruby -I/usr/home/rherna/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-support-3.8.0/lib:/usr/home/rherna/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib /usr/home
/rherna/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/openwrt/\*_spec.rb
                    
Command "which apinger 2> /dev/null"
  exit_status                  
    should eq 0
                                                             
Command "which bash 2> /dev/null"
  exit_status
    should eq 0                                          

Command "which logrotate 2> /dev/null"
  exit_status                          
    should eq 0
                                                
Command "which python3 2> /dev/null"              
  exit_status                                      
    should eq 0                                    
                                              
Command "which rsyslogd 2> /dev/null"                 
  exit_status                
    should eq 0                                       
                        
Command "which zabbix_agentd 2> /dev/null"                      
  exit_status                           
    should eq 0
                        
Command "pgrep apinger"                                         
  exit_status                           
    should eq 0     
                          
Command "pgrep crond"        
  exit_status                  
    should eq 0         
                                                 
Command "pgrep rsyslogd"       
  exit_status   
    should eq 0

Command "pgrep zabbix"
  exit_status
    should eq 0

File "/root/bin/wifi-details.sh"
  should exist
  should be mode 750
  should be owned by "root"
  should be grouped into "root"

Finished in 4.52 seconds (files took 0.71482 seconds to load)
14 examples, 0 failures
```

### ipq806x

Loaded firmware from `tftpd`:

```
BusyBox v1.30.0 () built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt SNAPSHOT, r0-ddf08af
 -----------------------------------------------------
root@OpenWrt:~# uname -a
Linux OpenWrt 4.14.93 #0 SMP Wed Feb 27 07:14:49 2019 armv7l GNU/Linux
root@OpenWrt:~# cat /etc/openwrt_version
r0-ddf08af
root@OpenWrt:~#  cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r0-ddf08af'
DISTRIB_TARGET='ipq806x/generic'
DISTRIB_ARCH='arm_cortex-a15_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r0-ddf08af'
DISTRIB_TAINTS='no-all busybox'
```

`serverspec`:

```
rake spec TEST_TYPE=openwrt TARGET_HOST=192.168.1.1                                                                       
/usr/home/rherna/.rbenv/versions/2.5.1/bin/ruby -I/usr/home/rherna/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-support-3.8.0/lib:/usr/home/rherna/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/lib /usr/home
/rherna/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rspec-core-3.8.0/exe/rspec --pattern spec/openwrt/\*_spec.rb                                                                             
                                                                                                                                                           
Command "which apinger 2> /dev/null"                                                                                                                                                            
  exit_status                                                                                                                                                                                   
    should eq 0                                                                                                                                            
                                                                                                                                                                                                
Command "which bash 2> /dev/null"                                                                                                                          
  exit_status                                                                                                                                                                                   
    should eq 0                                                                                
                                                                                                       
Command "which logrotate 2> /dev/null"                                                                                                                     
  exit_status                                                                                                                                                                                   
    should eq 0                                                                                        
                                                                                                                                                                                                
Command "which python3 2> /dev/null"                                                                                                                       
  exit_status                                                                                                                                                                                   
    should eq 0                                                                                                                                            
                                                                                                                                                                                                
Command "which rsyslogd 2> /dev/null"                                                                                                                      
  exit_status                                                                                                                                                                                   
    should eq 0                                                                                                                                                                                 
                                                                                                                                                           
Command "which zabbix_agentd 2> /dev/null"                                                                                                                                                      
  exit_status                                                                                                                                                                                                                           
    should eq 0                                                                                                                                            
                                                                                                                                                                                                
Command "pgrep apinger"                                                                                                                                                                         
  exit_status                                                                                          
    should eq 0                                                                                                                                            

Command "pgrep crond"
  exit_status
    should eq 0

Command "pgrep rsyslogd"
  exit_status
    should eq 0

Command "pgrep zabbix"
  exit_status
    should eq 0

File "/root/bin/wifi-details.sh"
  should exist
  should be mode 750
  should be owned by "root"
  should be grouped into "root"

Finished in 4.83 seconds (files took 0.44677 seconds to load)
14 examples, 0 failures
```

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
Thanks @owendelong ! Im hoping to get more of this going here in the next week or so! Should be pretty cool to have multi arch support

**Comment by sarcasticadmin** [comment]
@owendelong @kylerisse this is finally to a place where Im happy with it. It allows for building multiple architectures (ar71xx and ipq806x). Ive been able to validate that using the current example.yaml configs that can be found in `facts/secrets` the APs come up as intended and pass our tests! I had to battle with some issues with the upstream openwrt pkgs and that was kind of a time suck but Ive been the pkg repo to a semi newish version (Oct 2018) for the time being.

What I am still needing to work out is the networking configurations across both archs. But from everything Ive tested Im confident that that should be straight forward. Especially on the `ar71xx` since I have a serial connection now :tada: 

Anyway let me know what you think!

**Comment by owendelong** [comment]
Looks good to me... I'm hesitant, however, to dismiss Kyle's change request rather than let him do so.

**Comment by owendelong** [comment]
Guess Kyle took care of it while I was typing... Merged.

**Comment by sarcasticadmin** [comment]
Thanks @owendelong @kylerisse! Moving onto #142

**Pull request merged**
