### PR TITLE
Owen v0.0.5

### PR DESCRIPTION
**Pull request by owendelong**
## Description of PR
Completed initial pass at building switch configurations.

## Previous Behavior
Switch configurations weren't built

## New Behavior
Builds one test switch configuration to test libraries

## Tests
1. Grab monkey.
2. Obtain a large container of grease.
3. Apply grease to monkey.
4. Chase monkey.
5. Fun!
6. Place all captured monkeys in barrel for additional fun.

### CODE REVIEW

**Comment by owendelong** [comment]
I think this is ready to merge into master now.

**Comment by kylerisse** [comment]
Pulled down your branch. Tested by verifying script works with spot checking a couple switch types. Tested with the defaulted "NW-IDF", "BallroomA", and "Room211". All script output looked good. Also verified that IPv6 address expanded properly and that Base Input and Cooked Output output seems proper. I did note that changing DEBUGLEVEL had no effect but think that might be outside the scope of this PR. Let me know if there's anything else specific to test. I don't have hardware to load the config on to test validity and don't have much experience with Juniper to know if any glaring config issues are present. Looks good to me.

**Comment by owendelong** [comment]
If you change DEBUGLEVEL to 9, you'll notice some additional debugging output.
I need to go through and set more reasonable levels eventually, but for now, what I've been doing is setting the calls to debug that I'm not actively using to 9 and the ones I care about currently to 5.

I don't think there's anything else to test until we can load a config onto hardware.

**Comment by owendelong** [comment]
Can one of you approve this for merging? I'd like to get it merged and start a new branch from current master for further work.

**Comment by owendelong** [comment]
These changes are included in the pull request for owen-v0.0.6.

**Pull request closed without merging**
