### PR TITLE
[READY] - Bumping openwrt and opkg for 20x

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of PR

Fixes: #513 

Updating our openwrt image to latest commit off `master`

## Previous Behavior
- Previously set to a version of openwrt for 19x

## New Behavior
- Running latest build of openwrt on supported hardware for 20x
- Leverage a temporary fork of opkgs

## Tests
- Builds: https://github.com/socallinuxexpo/scale-network/actions/runs/3791195350
- Flashes against running hardware and all serverspec tests passing: https://gitlab.com/socallinuxexpo/scale-network/-/jobs/3531665684
- Client load test results: [results-1672250760.log](https://github.com/socallinuxexpo/scale-network/files/10315694/results-1672250760.log)

Speed summary from client results (only SUMs):
```
$ cat ~/Downloads/results-1672250760.log | grep SUM
[SUM]   0.00-1.00   sec  2.84 MBytes  23.8 Mbits/sec   79             
[SUM]   1.00-2.00   sec  2.42 MBytes  20.3 Mbits/sec    1             
[SUM]   2.00-3.00   sec  2.17 MBytes  18.2 Mbits/sec    0             
[SUM]   3.00-4.00   sec  1.74 MBytes  14.6 Mbits/sec    2             
[SUM]   4.00-5.00   sec  1.68 MBytes  14.1 Mbits/sec    5             
[SUM]   5.00-6.00   sec  1.62 MBytes  13.6 Mbits/sec    0             
[SUM]   6.00-7.00   sec  2.05 MBytes  17.2 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.17 MBytes  18.2 Mbits/sec    0             
[SUM]   8.00-9.00   sec  1.99 MBytes  16.7 Mbits/sec    0             
[SUM]   9.00-10.00  sec  1.86 MBytes  15.6 Mbits/sec    0             
[SUM]   0.00-10.00  sec  20.6 MBytes  17.2 Mbits/sec   87             sender
[SUM]   0.00-10.07  sec  18.7 MBytes  15.6 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  2.35 MBytes  19.7 Mbits/sec   20             
[SUM]   1.00-2.00   sec  2.55 MBytes  21.4 Mbits/sec    0             
[SUM]   2.00-3.00   sec  2.55 MBytes  21.4 Mbits/sec    0             
[SUM]   3.00-4.00   sec  1.49 MBytes  12.5 Mbits/sec    3             
[SUM]   4.00-5.00   sec  2.05 MBytes  17.2 Mbits/sec    1             
[SUM]   5.00-6.00   sec  1.68 MBytes  14.1 Mbits/sec    6             
[SUM]   6.00-7.00   sec  1.68 MBytes  14.1 Mbits/sec    3             
[SUM]   7.00-8.00   sec  1.30 MBytes  10.9 Mbits/sec    2             
[SUM]   8.00-9.00   sec  1.99 MBytes  16.7 Mbits/sec    0             
[SUM]   9.00-10.00  sec  1.55 MBytes  13.0 Mbits/sec    7             
[SUM]   0.00-10.00  sec  19.2 MBytes  16.1 Mbits/sec   42             sender
[SUM]   0.00-10.07  sec  18.5 MBytes  15.4 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  3.34 MBytes  28.0 Mbits/sec  107             
[SUM]   1.00-2.00   sec  2.30 MBytes  19.3 Mbits/sec    0             
[SUM]   2.00-3.00   sec  1.74 MBytes  14.6 Mbits/sec    0             
[SUM]   3.00-4.00   sec  1.43 MBytes  12.0 Mbits/sec    0             
[SUM]   4.00-5.00   sec  2.05 MBytes  17.2 Mbits/sec    1             
[SUM]   5.00-6.00   sec  2.42 MBytes  20.3 Mbits/sec    0             
[SUM]   6.00-7.00   sec  2.05 MBytes  17.2 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.36 MBytes  19.8 Mbits/sec    0             
[SUM]   8.00-9.00   sec  2.05 MBytes  17.2 Mbits/sec    4             
[SUM]   9.00-10.00  sec  1.80 MBytes  15.1 Mbits/sec    0             
[SUM]   0.00-10.00  sec  21.6 MBytes  18.1 Mbits/sec  112             sender
[SUM]   0.00-10.01  sec  20.2 MBytes  16.9 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  2.01 MBytes  16.8 Mbits/sec    5             
[SUM]   1.00-2.00   sec  1.62 MBytes  13.6 Mbits/sec    0             
[SUM]   2.00-3.00   sec  1.49 MBytes  12.5 Mbits/sec    1             
[SUM]   3.00-4.00   sec  2.11 MBytes  17.7 Mbits/sec    0             
[SUM]   4.00-5.00   sec  2.86 MBytes  24.0 Mbits/sec    0             
[SUM]   5.00-6.00   sec  2.05 MBytes  17.2 Mbits/sec   10             
[SUM]   6.00-7.00   sec  1.80 MBytes  15.1 Mbits/sec    2             
[SUM]   7.00-8.00   sec  2.49 MBytes  20.9 Mbits/sec    1             
[SUM]   8.00-9.00   sec  2.42 MBytes  20.3 Mbits/sec    1             
[SUM]   9.00-10.00  sec  2.73 MBytes  22.9 Mbits/sec    0             
[SUM]   0.00-10.00  sec  21.6 MBytes  18.1 Mbits/sec   20             sender
[SUM]   0.00-10.02  sec  20.4 MBytes  17.1 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  3.21 MBytes  27.0 Mbits/sec    2             
[SUM]   1.00-2.00   sec  2.24 MBytes  18.8 Mbits/sec   32             
[SUM]   2.00-3.00   sec  2.17 MBytes  18.2 Mbits/sec    1             
[SUM]   3.00-4.00   sec  3.04 MBytes  25.5 Mbits/sec   11             
[SUM]   4.00-5.00   sec  2.05 MBytes  17.2 Mbits/sec    0             
[SUM]   5.00-6.00   sec  2.49 MBytes  20.9 Mbits/sec    0             
[SUM]   6.00-7.00   sec  2.92 MBytes  24.5 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.55 MBytes  21.4 Mbits/sec    0             
[SUM]   8.00-9.00   sec  2.73 MBytes  22.9 Mbits/sec    1             
[SUM]   9.00-10.00  sec  2.61 MBytes  21.9 Mbits/sec    2             
[SUM]   0.00-10.00  sec  26.0 MBytes  21.8 Mbits/sec   49             sender
[SUM]   0.00-10.01  sec  24.7 MBytes  20.7 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  2.90 MBytes  24.3 Mbits/sec  182             
[SUM]   1.00-2.00   sec  3.48 MBytes  29.2 Mbits/sec   40             
[SUM]   2.00-3.00   sec  3.48 MBytes  29.2 Mbits/sec   32             
[SUM]   3.00-4.00   sec  2.42 MBytes  20.3 Mbits/sec    0             
[SUM]   4.00-5.00   sec  1.55 MBytes  13.0 Mbits/sec    0             
[SUM]   5.00-6.00   sec  2.55 MBytes  21.4 Mbits/sec    1             
[SUM]   6.00-7.00   sec  3.67 MBytes  30.8 Mbits/sec    0             
[SUM]   7.00-8.00   sec  3.11 MBytes  26.1 Mbits/sec    0             
[SUM]   8.00-9.00   sec  2.55 MBytes  21.4 Mbits/sec    0             
[SUM]   9.00-10.00  sec  1.55 MBytes  13.0 Mbits/sec    0             
[SUM]   0.00-10.00  sec  27.3 MBytes  22.9 Mbits/sec  255             sender
[SUM]   0.00-10.04  sec  25.3 MBytes  21.2 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  2.61 MBytes  21.9 Mbits/sec   24             
[SUM]   1.00-2.00   sec  2.24 MBytes  18.8 Mbits/sec    7             
[SUM]   2.00-3.00   sec  2.73 MBytes  22.9 Mbits/sec    1             
[SUM]   3.00-4.00   sec  2.55 MBytes  21.4 Mbits/sec    5             
[SUM]   4.00-5.00   sec  2.92 MBytes  24.5 Mbits/sec    0             
[SUM]   5.00-6.00   sec  2.36 MBytes  19.8 Mbits/sec    4             
[SUM]   6.00-7.00   sec  2.73 MBytes  22.9 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.73 MBytes  22.9 Mbits/sec    0             
[SUM]   8.00-9.00   sec  2.67 MBytes  22.4 Mbits/sec   15             
[SUM]   9.00-10.00  sec  2.17 MBytes  18.2 Mbits/sec    0             
[SUM]   0.00-10.00  sec  25.7 MBytes  21.6 Mbits/sec   56             sender
[SUM]   0.00-10.02  sec  24.7 MBytes  20.7 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  4.71 MBytes  39.5 Mbits/sec  202             
[SUM]   1.00-2.00   sec  3.48 MBytes  29.2 Mbits/sec    0             
[SUM]   2.00-3.00   sec  2.86 MBytes  24.0 Mbits/sec    0             
[SUM]   3.00-4.00   sec  3.73 MBytes  31.3 Mbits/sec    0             
[SUM]   4.00-5.00   sec  2.49 MBytes  20.8 Mbits/sec    0             
[SUM]   5.00-6.00   sec  2.30 MBytes  19.3 Mbits/sec    1             
[SUM]   6.00-7.00   sec  3.04 MBytes  25.5 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.61 MBytes  21.9 Mbits/sec    0             
[SUM]   8.00-9.00   sec  2.24 MBytes  18.8 Mbits/sec    1             
[SUM]   9.00-10.00  sec  2.05 MBytes  17.2 Mbits/sec    0             
[SUM]   0.00-10.00  sec  29.5 MBytes  24.8 Mbits/sec  204             sender
[SUM]   0.00-10.04  sec  27.4 MBytes  22.9 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  2.97 MBytes  24.9 Mbits/sec   73             
[SUM]   1.00-2.00   sec  1.49 MBytes  12.5 Mbits/sec   25             
[SUM]   2.00-3.00   sec  1.55 MBytes  13.0 Mbits/sec    5             
[SUM]   3.00-4.00   sec  2.36 MBytes  19.8 Mbits/sec    1             
[SUM]   4.00-5.00   sec  1.55 MBytes  13.0 Mbits/sec    5             
[SUM]   5.00-6.00   sec  1.99 MBytes  16.7 Mbits/sec    0             
[SUM]   6.00-7.00   sec  1.99 MBytes  16.7 Mbits/sec    0             
[SUM]   7.00-8.00   sec  1.99 MBytes  16.7 Mbits/sec    0             
[SUM]   8.00-9.00   sec  2.30 MBytes  19.3 Mbits/sec    0             
[SUM]   9.00-10.00  sec  2.67 MBytes  22.4 Mbits/sec    0             
[SUM]   0.00-10.00  sec  20.9 MBytes  17.5 Mbits/sec  109             sender
[SUM]   0.00-10.03  sec  19.3 MBytes  16.2 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  3.26 MBytes  27.4 Mbits/sec   44             
[SUM]   1.00-2.00   sec  1.74 MBytes  14.6 Mbits/sec   16             
[SUM]   2.00-3.00   sec  2.61 MBytes  21.9 Mbits/sec    0             
[SUM]   3.00-4.00   sec  2.61 MBytes  21.9 Mbits/sec   18             
[SUM]   4.00-5.00   sec  2.11 MBytes  17.7 Mbits/sec    1             
[SUM]   5.00-6.00   sec  2.86 MBytes  24.0 Mbits/sec    0             
[SUM]   6.00-7.00   sec  2.67 MBytes  22.4 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.92 MBytes  24.5 Mbits/sec    1             
[SUM]   8.00-9.00   sec  2.11 MBytes  17.7 Mbits/sec    1             
[SUM]   9.00-10.00  sec  2.86 MBytes  24.0 Mbits/sec    2             
[SUM]   0.00-10.00  sec  25.8 MBytes  21.6 Mbits/sec   83             sender
[SUM]   0.00-10.03  sec  24.0 MBytes  20.1 Mbits/sec                  receiver
[SUM]   0.00-1.00   sec  4.80 MBytes  40.2 Mbits/sec  109             
[SUM]   1.00-2.00   sec  3.11 MBytes  26.1 Mbits/sec   42             
[SUM]   2.00-3.00   sec  2.67 MBytes  22.4 Mbits/sec    0             
[SUM]   3.00-4.00   sec  2.36 MBytes  19.8 Mbits/sec    0             
[SUM]   4.00-5.00   sec  3.23 MBytes  27.1 Mbits/sec    1             
[SUM]   5.00-6.00   sec  1.49 MBytes  12.5 Mbits/sec    0             
[SUM]   6.00-7.00   sec  3.42 MBytes  28.7 Mbits/sec    0             
[SUM]   7.00-8.00   sec  2.80 MBytes  23.5 Mbits/sec    7             
[SUM]   8.00-9.00   sec  3.23 MBytes  27.1 Mbits/sec   26             
[SUM]   9.00-10.00  sec  3.42 MBytes  28.7 Mbits/sec    0             
[SUM]   0.00-10.00  sec  30.5 MBytes  25.6 Mbits/sec  185             sender
[SUM]   0.00-10.05  sec  27.2 MBytes  22.7 Mbits/sec                  receiver
```

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
Not bad! Initial testing for these new versions seem to check out in the serverspec tests minus 1 failure from apinger: https://gitlab.com/socallinuxexpo/scale-network/-/jobs/3528591976#L272

```
Failures:
  1) shared Command "pgrep apinger" exit_status is expected to eq 0
     On host `192.168.254.100'
     Failure/Error: its(:exit_status) { should eq 0 }
       
       expected: 0
            got: 1
       
       (compared using ==)
       /bin/sh -c pgrep\ apinger
       
     Shared Example Group: "openwrt" called from ./spec/openwrt/init_spec.rb:13
     # ./spec/shared/openwrt/init.rb:28:in `block (4 levels) in <top (required)>'
Finished in 7.3 seconds (files took 5.41 seconds to load)
53 examples, 1 failure
```

Will look into this now to see whats going on with that daemon

**Comment by sarcasticadmin** [comment]
Opened up the following issue with opkg for `apinger`: https://github.com/openwrt/packages/issues/20184

It looks like the updates to the `apinger` daemon no longer look for the default config in `/etc/apinger`

**Comment by sarcasticadmin** [comment]
@owendelong I believe this is in a good state and have it this most current build being dogfood on my home network now. Everything checked out :shipit:

**Review by owendelong — APPROVED** [review]
Great work, Rob!

Does this mean we have code freeze?

**Pull request merged**
