### PR TITLE
[WAIT] Initial checkpoint of port Map generation, SCaLE 17x router configuration backups

### PR DESCRIPTION
**Pull request by owendelong**
## Description of PR
I thought this had already been merged. It should get merged before OD.18.02 or we lose some history.

## New Behavior
Backed up router configs from SCALE17x
Initial checkpoint of switch port map generation
Removal of secret data from router backups

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
@owendelong somethings not right here, i believe some of this was merged in https://github.com/socallinuxexpo/scale-network/pull/265

**Comment by owendelong** [comment]
It might have been... I was going through old branches and cleaning stuff up and found diffs for this branch that apparently weren't merged. It looked like merging those would be useful and didn't create a problem.

**Comment by sarcasticadmin** [comment]
@owendelong well i cant merge it since theres conflicts, so we will have to resolve these. Before we do anything

**Comment by owendelong** [comment]
I just resolved the 1 conflict.

**Comment by owendelong** [comment]
Do not merge.

**Comment by sarcasticadmin** [comment]
closing after talking with @owendelong

**Pull request closed without merging**
