### PR TITLE
[READY] nix.treewide: remove flake-parts

### PR DESCRIPTION
**Pull request by djacu**
## Description of PR

Removes flake parts and restructures the nix sections of the repository.

## Previous Behavior

Absolute chaos

## New Behavior

Bringing structure and order to the architecture of the nix code.
The hope is that this PR is effectively a no-op and the packages, NixOS configurations, and checks are the same.
Testing in comments below found that the only remaining differences are NixOS system closures revolving around:
- `berkhan` being added as a user to all systems
- system packages being different which is very likely attributed to `berkhan` being added (e.g. a single new instance of bash showed up) OR system packages being strings and order had changed for no reason (using `jd` confirmed that the package set was identical in the few cases that were tested)
- the hostname changed because now there is a default for all hosts 

## Tests

`nix flake check`
Lots more see below

### CODE REVIEW

**Comment by djacu** [comment]
small PR
didn't change much :P

**Comment by djacu** [comment]
A script has been written to compare the closures of all the packages and nixos systems listed below.

```bash
> cat closure-compare.sh      
my_array=(
  "massflash"
  "serverspec"
  "scaleInventory"
  "nixosConfigurations.bootstrapImage.config.system.build.toplevel"
  "nixosConfigurations.cache.config.system.build.toplevel"
  "nixosConfigurations.coreMaster.config.system.build.toplevel"
  "nixosConfigurations.coreSlave.config.system.build.toplevel"
  "nixosConfigurations.devServer.config.system.build.toplevel"
  "nixosConfigurations.hypervisor1.config.system.build.toplevel"
  "nixosConfigurations.hypervisor2.config.system.build.toplevel"
  "nixosConfigurations.loghost.config.system.build.toplevel"
  "nixosConfigurations.massflash.config.system.build.toplevel"
  "nixosConfigurations.monitor.config.system.build.toplevel"
  "nixosConfigurations.signs.config.system.build.toplevel"
)

currentBranch="djacu/remove-flake-parts"

for attrPath in "${my_array[@]}"; do
  echo "$attrPath"
  git switch -q master
  nix eval .\#"$attrPath".drvPath
  git switch -q "$currentBranch"
  nix eval .\#"$attrPath".drvPath
  echo ""
done
```

Here is the output from running the script as of commit 960ce8a26aeae941cf13828d3464d38ff77a8acd 
All packages have identical derivations.
All nixos systems have differing derivations. These will be investigated.

```
> ./closure-compare.sh
massflash
"/nix/store/npbypaazrs3c1w7r22wfxwyhrqi9da34-massflash.drv"
"/nix/store/npbypaazrs3c1w7r22wfxwyhrqi9da34-massflash.drv"

serverspec
"/nix/store/36gi6ig093skz6qvgghm826dgga9qzsy-serverspec.drv"
"/nix/store/36gi6ig093skz6qvgghm826dgga9qzsy-serverspec.drv"

scaleInventory
"/nix/store/ypfmidmvag36m79iyx11lan5j2wkykj3-scaleInventory.drv"
"/nix/store/ypfmidmvag36m79iyx11lan5j2wkykj3-scaleInventory.drv"

nixosConfigurations.bootstrapImage.config.system.build.toplevel
"/nix/store/ii7hiz8rg5af13wzckr2j65vvd53amdx-nixos-system-nixos-24.05.20241009.d51c286.drv"
"/nix/store/1fj68fj0iyk0clp441aapn4md1dnvan1-nixos-system-bootstrap-image-24.05.20241009.d51c286.drv"

nixosConfigurations.cache.config.system.build.toplevel
"/nix/store/v9s7fyl6if1265xg31lr5117l4fk48nj-nixos-system-cache-24.05.20241009.d51c286.drv"
"/nix/store/6y7kyaf4rjpib6cx2acfwvfpg2f958b0-nixos-system-cache-24.05.20241009.d51c286.drv"

nixosConfigurations.coreMaster.config.system.build.toplevel
"/nix/store/gr497xjzacpf1d3ng7kn9j7sv2k1cccw-nixos-system-coremaster-24.05.20241009.d51c286.drv"
"/nix/store/ncbgzrm3nb5995q1zr23905bdilsyysa-nixos-system-coremaster-24.05.20241009.d51c286.drv"

nixosConfigurations.coreSlave.config.system.build.toplevel
"/nix/store/bhvr2c5xhr6slbgynps2dn7mflg962kp-nixos-system-coreslave-24.05.20241009.d51c286.drv"
"/nix/store/c3yqwnsxp2mfvkjdmac4cayrr5zwq1v5-nixos-system-coreslave-24.05.20241009.d51c286.drv"

nixosConfigurations.devServer.config.system.build.toplevel
"/nix/store/k61k9flcr0rap7csig785ml39wd420f3-nixos-system-nixos-24.05.20241009.d51c286.drv"
"/nix/store/hn353g2cwfbzm3067c39q86xjdbxz5g1-nixos-system-dev-server-24.05.20241009.d51c286.drv"

nixosConfigurations.hypervisor1.config.system.build.toplevel
"/nix/store/i5y71ybc8nr6vnkbqndq3ylhy6canniv-nixos-system-nixos-24.05.20241009.d51c286.drv"
"/nix/store/0ass3v4qar1c9yp881lmfydfzvghyvn8-nixos-system-hypervisor1-24.05.20241009.d51c286.drv"

nixosConfigurations.hypervisor2.config.system.build.toplevel
"/nix/store/zwnbrs40lgvpnfgah46qafzq98hm702b-nixos-system-nixos-24.05.20241009.d51c286.drv"
"/nix/store/1ppyi7si7hz6x4bqikms9pk310nwccd5-nixos-system-hypervisor2-24.05.20241009.d51c286.drv"

nixosConfigurations.loghost.config.system.build.toplevel
"/nix/store/asrn05w714bb2nhm5x2h3m9gljcs62fk-nixos-system-nixos-24.05.20241009.d51c286.drv"
"/nix/store/4iricdywiq5pl453zg921cymngs4fq6n-nixos-system-loghost-24.05.20241009.d51c286.drv"

nixosConfigurations.massflash.config.system.build.toplevel
"/nix/store/q1ic3m9jizglwbg5j61r5gf00gg4g458-nixos-system-massflash-24.05.20241009.d51c286.drv"
"/nix/store/vlv5v250k5daq2dnhj3bzn7p5dnsrg2f-nixos-system-massflash-24.05.20241009.d51c286.drv"

nixosConfigurations.monitor.config.system.build.toplevel
"/nix/store/giyxwraih51pilcprqvz31msml8jl0n4-nixos-system-monitor-24.05.20241009.d51c286.drv"
"/nix/store/vx021gijq5f0c4575jq4na4ffifs0c36-nixos-system-monitor-24.05.20241009.d51c286.drv"

nixosConfigurations.signs.config.system.build.toplevel
"/nix/store/hzcx0rj654hsdmx4v7zz0y749d74w1k5-nixos-system-nixos-24.05.20241009.d51c286.drv"
"/nix/store/6ijq714jjcpprgm9xph6zivs97b9b6k4-nixos-system-signs-24.05.20241009.d51c286.drv"
```

**Comment by djacu** [comment]
Reviewing the `signs` nixos system, there are 3 differences.
1. The hostname
2. The users
3. The packages

The hostname differs because it was previously unset and defaults to `nixos`. Now all system closures set a hostname that matches the directory where the configuration is stored.

The users differ because of the addition of `berkhan` to all nixos systems.

```
> git switch master
> nix eval .\#nixosConfigurations.signs.config.users.users --json > old.json
> git switch djacu/remove-flake-parts
> nix eval .\#nixosConfigurations.signs.config.users.users --json > new.json
> diff <(jq --sort-keys . old.json) <(jq --sort-keys . new.json)
1a2,41
>   "berkhan": {
>     "autoSubUidGidRange": true,
>     "createHome": true,
>     "cryptHomeLuks": null,
>     "description": "",
>     "expires": null,
>     "extraGroups": [
>       "wheel"
>     ],
>     "group": "users",
>     "hashedPassword": null,
>     "hashedPasswordFile": null,
>     "home": "/home/berkhan",
>     "homeMode": "700",
>     "ignoreShellProgramCheck": false,
>     "initialHashedPassword": null,
>     "initialPassword": null,
>     "isNormalUser": true,
>     "isSystemUser": false,
>     "linger": false,
>     "name": "berkhan",
>     "openssh": {
>       "authorizedKeys": {
>         "keyFiles": [],
>         "keys": [
>           "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH6UhZ/oPqiFzCOxoZWeUqeGZCVLLNQbHH3uuIa6PCTz"
>         ]
>       },
>       "authorizedPrincipals": []
>     },
>     "packages": [],
>     "pamMount": {},
>     "password": null,
>     "passwordFile": null,
>     "shell": "/nix/store/1av86b17lymgk29s85nhgxsmfvmxympz-bash-interactive-5.2p32",
>     "subGidRanges": [],
>     "subUidRanges": [],
>     "uid": 2100,
>     "useDefaultShell": true
>   },
```

The packages differ most likely because of the addition of `berkhan`. You can see it has the same nix store path as the `shell` attribute above.

```
> git switch master
> nix eval .\#nixosConfigurations.signs.config.system.path.pkgs --json | jq '. | fromjson' > old.json
> git switch djacu/remove-flake-parts
> nix eval .\#nixosConfigurations.signs.config.system.path.pkgs --json | jq '. | fromjson' > new.json
> diff <(jq --sort-keys . old.json) <(jq --sort-keys . new.json)
449a450,456
>       "/nix/store/1av86b17lymgk29s85nhgxsmfvmxympz-bash-interactive-5.2p32",
>       "/nix/store/9kwv0awas93y7fsfscfdilfc7zk5ibk5-bash-interactive-5.2p32-man"
>     ],
>     "priority": 5
>   },
>   {
>     "paths": [
```

**Comment by djacu** [comment]
The `monitor` system alleges to have changes in the system path packages but comparing the differences as was done above shows no difference I can see.


```
> diff <(jq --sort-keys . old.json) <(jq --sort-keys . new.json)
3a4,23
>       "/nix/store/nz9s8hw4v8lv9a315kppqlixail8nrgk-vim-9.1.0707",
>       "/nix/store/2i2d495si9dygvzaskwyrvxaxkvi9k55-vim-9.1.0707-xxd"
>     ],
>     "priority": 5
>   },
>   {
>     "paths": [
>       "/nix/store/vdd8ccp9x69v7kp5g9khq7j43n6dqf16-git-2.44.1"
>     ],
>     "priority": 5
>   },
>   {
>     "paths": [
>       "/nix/store/w0k2k9x26wzv18c3zkvgcg3zqksq4mln-binutils-wrapper-2.41",
>       "/nix/store/2jq4kzrf5nbdxk7pzwi8di07h4f4a0ix-binutils-wrapper-2.41-man"
>     ],
>     "priority": 10
>   },
>   {
>     "paths": [
182,201d201
<   },
<   {
<     "paths": [
<       "/nix/store/nz9s8hw4v8lv9a315kppqlixail8nrgk-vim-9.1.0707",
<       "/nix/store/2i2d495si9dygvzaskwyrvxaxkvi9k55-vim-9.1.0707-xxd"
<     ],
<     "priority": 5
<   },
<   {
<     "paths": [
<       "/nix/store/vdd8ccp9x69v7kp5g9khq7j43n6dqf16-git-2.44.1"
<     ],
<     "priority": 5
<   },
<   {
<     "paths": [
<       "/nix/store/w0k2k9x26wzv18c3zkvgcg3zqksq4mln-binutils-wrapper-2.41",
<       "/nix/store/2jq4kzrf5nbdxk7pzwi8di07h4f4a0ix-binutils-wrapper-2.41-man"
<     ],
<     "priority": 10
```

**Comment by djacu** [comment]
`massflash`, `loghost`, `hypervisor2`, `coreSlave`, `cache`, and `bootstrapImage` appear to have the same differences in hostname, users, and system path packages as `signs`. This was not thoroughly checked but the outputs of `nix-diff` appear similar and can easily be explained by the addition of `berkhan`.

`hypervisor1`, `devServer`, `coreMaster`, potentially have significant differences.

**Review by kylerisse — COMMENTED** [review]
@djacu Here is my testing output. `nix flake check` worked but had the warnings below. `nix develop` also worked. Not sure if those warnings are important. I included a `nix-info` output as it might be something related to 24.11 or my version of `cppnix`. @sarcasticadmin will likely have more comprehensive testing but so far it doesn't appear anything broke at a high level. Please let me know if there's anything specific you want tested.

```
kylerisse@watson ~/g/s/g/k/scale-network (djacu/remove-flake-parts) [SIGHUP]> nix flake check
warning: unknown flake output 'formatterModule'
warning: unknown flake output 'library'
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
warning: The check omitted these incompatible systems: aarch64-darwin, aarch64-linux, x86_64-darwin
Use '--all-systems' to check all.
kylerisse@watson ~/g/s/g/k/scale-network (djacu/remove-flake-parts)> nix shell nixpkgs#nix-info --command nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.11.7, NixOS, 24.11 (Vicuna), 24.11.20241116.057f63b`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/idq1bmwwy9rlkc21hccvx42wlwpxsx1f-source`

kylerisse@watson ~/g/s/g/k/scale-network (djacu/remove-flake-parts)> git lsha
960ce8a26aeae941cf13828d3464d38ff77a8acd
kylerisse@watson ~/g/s/g/k/scale-network (djacu/remove-flake-parts)> nix develop
[nix-flakes scale-network] $ exit
exit
```

**Comment by djacu** [comment]
@kylerisse thanks for review the changes. @sarcasticadmin and I aren't seeing the warnings about neovim-unwrapped. Here is the output for `nix flake check` from me.

```
djacu@malachite:~/dev/socallinuxexpo/scale-network/ > nix flake check                                                                                      
warning: unknown flake output 'formatterModule'
warning: unknown flake output 'library'
warning: The check omitted these incompatible systems: aarch64-darwin, aarch64-linux, x86_64-darwin
Use '--all-systems' to check all.
djacu@malachite:~/dev/socallinuxexpo/scale-network/ > rg neovim    
djacu@malachite:~/dev/socallinuxexpo/scale-network/ > rg nvim  
djacu@malachite:~/dev/socallinuxexpo/scale-network/ > rg unwrapped
```

The neovim-unwrapped warning seems to be an upstream issue. I found a downstream issue related to it here. https://github.com/nix-community/nixvim/issues/2037

**Comment by djacu** [comment]
@kylerisse are you using neovim-unwrapped in your system?

**Review by sarcasticadmin — APPROVED** [review]
I paired with @djacu and we worked through any of the outstanding diffs. This is by and large a no-op (thank you @djacu for going above and beyond on this front).

@socallinuxexpo/tech If anyone wants to give this a review, feel free to try building locally with: `nix flake check -L` :rocket:

**Comment by djacu** [comment]
1. I like being spit on my face ;) 
2. This is part of a larger effort to bring better organization and structure to the repository. Looking back on the PR that added flake-parts, it did simply some of the structure, but did not fix many underlying organizational issues. @sarcasticadmin, @kylerisse, and myself don't have a good handle on flake-parts yet and it is easier to architect the repository into a better state using plain nix code for now. It is on my list to learn and something we can look at in the future when the repository is in a better state.

**Comment by MatthewCroughan** [comment]
Yeah awesome, it's about what works for the people doing the active work on the repo. I can help re-introduce it again in the future, if the need arises, which I think it will.

**Comment by djacu** [comment]
Thanks man. We'll definitely be calling on you for your expertise 🙏

**Comment by kylerisse** [comment]
> @kylerisse are you using neovim-unwrapped in your system?

had `neovim` on the system, removed it to test this, same thing. i didn't consider my local system beyond what I pasted from `nix-info` but you're probably right that it's something specific to my config if nobody can recreate it. just weird that it happens even after removing `neovim`, and also I don't explicitly use `neovim-unwrapped`.

Here's more verbose output:

```
> nix flake check -L --verbose
(...omit for brevity...)
checking flake output 'formatter'...
checking flake output 'formatterModule'...
warning: unknown flake output 'formatterModule'
checking flake output 'legacyPackages'...
checking flake output 'library'...
warning: unknown flake output 'library'
checking flake output 'nixosConfigurations'...
checking NixOS configuration 'nixosConfigurations.loghost'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.massflash'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.monitor'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.cache'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.hypervisor1'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.hypervisor2'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.signs'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.bootstrapImage'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.coreMaster'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.coreSlave'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
checking NixOS configuration 'nixosConfigurations.devServer'...
warning: In a derivation named 'neovim-unwrapped-0.9.5', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead
(...omit for brevity...)
```

```
> nix shell nixpkgs#nix-info --command nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.1, NixOS, 24.11 (Vicuna), 24.11.20241123.0c58267`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.10`
 - channels(root): `"nixos"`
 - nixpkgs: `/nix/store/fnbr9s78sy4islw83vsaf0hgf88hih5v-source`
```

Like I said initially, they're just warnings and nothing fails. I'm just perplexed that it's even related at this phase as it should be pretty sandboxed no? and neovim isn't used for SCaLE AFAIK. Nothing I'm worried about or want to spend further time on though if you two say it's OK. Let me know if you need further testing or info though.

**Review by kylerisse — APPROVED** [review]

**Comment by sarcasticadmin** [comment]
Thanks for the reviews @MatthewCroughan and @kylerisse sounds like were all the same page and this restructuring its a big improvement from where we were. `flake-parts` can definitely be reintroduced whenever we need it 🙂 

@djacu thanks again for all the effort, Im excited to have this land in `master`

**Pull request merged**
